---
- name: Deploy application with Docker Compose
  hosts: all
  become: true
  vars:
    repo_url: "https://github.com/Elias-Belkheiri/Cloudy-one"
    project_dir: "/opt/Cloudy-one"
    compose_dir: "{{ project_dir }}/docker"

  tasks:
    - name: Create project directory
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: "0755"

    - name: Clone/Pull repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        force: yes
        version: main

    - name: Copy .env file if it exists locally
      copy:
        src: ../.env
        dest: "{{ compose_dir }}/.env"
      ignore_errors: yes

    - name: build and run the containers
      ansible.builtin.command: chdir=/opt/Cloudy-one/docker docker compose up --build -d
      register: docker_result
    - name: Display the output
      debug:
        msg: "{{ docker_result.stdout }}"