---
- name: Install Docker on Ubuntu
  hosts: all
  become: true
  remote_user: root
  tasks:
    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - git
        state: latest
    - name: Add Docker GPG apt Key
      ansible.builtin.shell:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg
    - name: Add docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable"
        state: present
    - name: Install docker
      ansible.builtin.apt:
        name: docker-ce
        state: latest
    - name: Start docker service
      ansible.builtin.service:
        name: docker
        state: started
    - name: enable docker service
      ansible.builtin.service:
        name: docker
        enabled: true
    - name: Add the user vagrant to docker group
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: yes
